export {MissionSection} from "./Mission/MissionSection"
export {FeaturesSection} from "./Features/FeaturesSection"
export {HowToSection} from "./HowTo/HowToSection" 
export {NewsSection} from "./News/NewsSection"
export {TeamSection} from "./Team/TeamSection"
export {FaqSection} from "./Faq/FaqSection"
export {ContactSection} from "./Contact/ContactSection"
export {MainSection} from "./Main/MainSection"
